/**
 * Trick question/puzzle bank for Brain Out
 *
 * Each puzzle has a tricky question with a surprising answer.
 * The key is that the "obvious" answer is wrong — players need lateral thinking.
 */

import type { Puzzle } from '../types';

export const PUZZLES: Puzzle[] = [
  // ─── Stage 1: Easy (difficulty 1) ─────────────────────
  {
    id: 1,
    question: '가장 큰 숫자를 탭하세요',
    hint: '화면에 보이는 숫자의 크기가 아닙니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '3', x: 0.2, y: 0.3 },
      { id: 'b', label: '15', x: 0.5, y: 0.5 },
      { id: 'c', label: '7', x: 0.8, y: 0.3 },
      { id: 'd', label: '99', x: 0.5, y: 0.7 },
    ],
    correctIds: ['d'],
    explanation: '99가 가장 큰 숫자입니다. 글자 크기에 속지 마세요!',
    difficulty: 1,
  },
  {
    id: 2,
    question: '냉장고에 코끼리를 넣으려면?',
    hint: '문을 열어야 합니다',
    interaction: 'sequence',
    choices: [
      { id: 'open', label: '문 열기', x: 0.5, y: 0.3 },
      { id: 'put', label: '코끼리 넣기', x: 0.5, y: 0.5 },
      { id: 'close', label: '문 닫기', x: 0.5, y: 0.7 },
    ],
    correctIds: ['open', 'put', 'close'],
    explanation: '문 열기 → 코끼리 넣기 → 문 닫기. 순서대로!',
    difficulty: 1,
  },
  {
    id: 3,
    question: '어떤 것이 가장 어둡나요?',
    hint: '화면을 잘 보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '☀️', x: 0.25, y: 0.4 },
      { id: 'b', label: '🌙', x: 0.5, y: 0.4 },
      { id: 'c', label: '💡', x: 0.75, y: 0.4 },
      { id: 'd', label: '⬛', x: 0.5, y: 0.65 },
    ],
    correctIds: ['d'],
    explanation: '검은색 사각형이 가장 어둡습니다!',
    difficulty: 1,
  },
  {
    id: 4,
    question: '삼각형은 몇 개인가요?',
    hint: '큰 삼각형 안의 작은 삼각형도 세어보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '7', x: 0.2, y: 0.7 },
      { id: 'b', label: '9', x: 0.4, y: 0.7 },
      { id: 'c', label: '11', x: 0.6, y: 0.7 },
      { id: 'd', label: '0', x: 0.8, y: 0.7 },
    ],
    correctIds: ['c'],
    explanation: '크고 작은 삼각형을 모두 세면 11개입니다!',
    difficulty: 1,
  },
  {
    id: 5,
    question: '가장 빨간 것을 탭하세요',
    hint: '"빨간"이라는 글자도 빨갈 수 있습니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🍎', x: 0.25, y: 0.4 },
      { id: 'b', label: '❤️', x: 0.5, y: 0.4 },
      { id: 'c', label: '빨간', x: 0.75, y: 0.4 },
    ],
    correctIds: ['c'],
    explanation: '"빨간"이라는 글자 자체가 답입니다!',
    difficulty: 1,
  },

  // ─── Stage 2: Easy-Medium (difficulty 1-2) ────────────
  {
    id: 6,
    question: '1+2+3+...+10 = ?',
    hint: '계산해보세요! 1부터 10까지의 합',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '45', x: 0.2, y: 0.5 },
      { id: 'b', label: '50', x: 0.4, y: 0.5 },
      { id: 'c', label: '55', x: 0.6, y: 0.5 },
      { id: 'd', label: '100', x: 0.8, y: 0.5 },
    ],
    correctIds: ['c'],
    explanation: '1+2+3+...+10 = 55. 가우스 공식: n(n+1)/2 = 55',
    difficulty: 1,
  },
  {
    id: 7,
    question: '성냥 1개를 움직여 가장 큰 수를 만드세요: 508',
    hint: '0에서 성냥 하나를 빼면...',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '588', x: 0.2, y: 0.5 },
      { id: 'b', label: '568', x: 0.4, y: 0.5 },
      { id: 'c', label: '909', x: 0.6, y: 0.5 },
      { id: 'd', label: '518', x: 0.8, y: 0.5 },
    ],
    correctIds: ['c'],
    explanation: '0에서 성냥 하나를 빼서 5를 9로 만들면 909!',
    difficulty: 2,
  },
  {
    id: 8,
    question: '아이스크림에서 가장 위에 있는 것은?',
    hint: '문제를 다시 읽어보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '체리', x: 0.25, y: 0.4 },
      { id: 'b', label: '크림', x: 0.5, y: 0.4 },
      { id: 'c', label: '"아"', x: 0.75, y: 0.4 },
    ],
    correctIds: ['c'],
    explanation: '"아이스크림"에서 가장 위(처음)에 있는 것은 "아"!',
    difficulty: 2,
  },
  {
    id: 9,
    question: '물음표에 들어갈 숫자는? 2, 4, 8, 16, ?',
    hint: '각 숫자는 이전 숫자의 2배입니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '24', x: 0.2, y: 0.5 },
      { id: 'b', label: '30', x: 0.4, y: 0.5 },
      { id: 'c', label: '32', x: 0.6, y: 0.5 },
      { id: 'd', label: '20', x: 0.8, y: 0.5 },
    ],
    correctIds: ['c'],
    explanation: '2×2=4, 4×2=8, 8×2=16, 16×2=32',
    difficulty: 1,
  },
  {
    id: 10,
    question: '양초 10개 중 3개를 불어서 끄면 몇 개가 남나요?',
    hint: '꺼진 양초는 녹지 않습니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '7', x: 0.2, y: 0.5 },
      { id: 'b', label: '3', x: 0.4, y: 0.5 },
      { id: 'c', label: '10', x: 0.6, y: 0.5 },
      { id: 'd', label: '0', x: 0.8, y: 0.5 },
    ],
    correctIds: ['b'],
    explanation: '나머지 7개는 타서 없어지고, 끈 3개만 남습니다!',
    difficulty: 2,
  },

  // ─── Stage 3: Medium (difficulty 2) ───────────────────
  {
    id: 11,
    question: '1000에 40을 더하세요. 거기에 1000을 더하세요.\n20을 더하고, 다시 1000을 더하세요.\n10을 더하면?',
    hint: '천천히 다시 계산해보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '5000', x: 0.2, y: 0.6 },
      { id: 'b', label: '4070', x: 0.4, y: 0.6 },
      { id: 'c', label: '3070', x: 0.6, y: 0.6 },
      { id: 'd', label: '4100', x: 0.8, y: 0.6 },
    ],
    correctIds: ['c'],
    explanation: '1000+40=1040, +1000=2040, +20=2060, +1000=3060, +10=3070. 대부분 5000으로 착각!',
    difficulty: 2,
  },
  {
    id: 12,
    question: '어떤 컵에 물이 가장 먼저 차나요?\n(파이프가 연결된 그림)',
    hint: '파이프의 막힌 곳을 잘 보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '컵 1', x: 0.15, y: 0.5 },
      { id: 'b', label: '컵 2', x: 0.38, y: 0.5 },
      { id: 'c', label: '컵 3', x: 0.62, y: 0.5 },
      { id: 'd', label: '컵 5', x: 0.85, y: 0.5 },
    ],
    correctIds: ['d'],
    explanation: '파이프가 막혀있어서 컵 5에만 물이 갑니다!',
    difficulty: 2,
  },
  {
    id: 13,
    question: '9시 방향의 시계를 탭하세요',
    hint: '시계 바늘이 9시를 가리키는 것을 찾으세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🕐', x: 0.2, y: 0.4 },
      { id: 'b', label: '🕘', x: 0.5, y: 0.4 },
      { id: 'c', label: '🕕', x: 0.8, y: 0.4 },
    ],
    correctIds: ['b'],
    explanation: '🕘가 9시 방향을 가리킵니다!',
    difficulty: 2,
  },
  {
    id: 14,
    question: '다음 중 먹을 수 없는 것은?',
    hint: '그릇도 먹을 수 없습니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🍕', x: 0.2, y: 0.4 },
      { id: 'b', label: '🍔', x: 0.4, y: 0.4 },
      { id: 'c', label: '🍽️', x: 0.6, y: 0.4 },
      { id: 'd', label: '🍰', x: 0.8, y: 0.4 },
    ],
    correctIds: ['c'],
    explanation: '접시(🍽️)는 먹을 수 없습니다!',
    difficulty: 2,
  },
  {
    id: 15,
    question: '모기를 잡으세요! 🦟',
    hint: '화면의 모기를 직접 탭하세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🦟', x: 0.3, y: 0.35 },
      { id: 'b', label: '🐝', x: 0.7, y: 0.35 },
      { id: 'c', label: '🦋', x: 0.3, y: 0.6 },
      { id: 'd', label: '🐛', x: 0.7, y: 0.6 },
    ],
    correctIds: ['a'],
    explanation: '모기(🦟)를 직접 탭해서 잡았습니다!',
    difficulty: 2,
  },

  // ─── Stage 4: Medium-Hard (difficulty 2-3) ────────────
  {
    id: 16,
    question: '아래 사진에서 닭은 몇 마리?',
    hint: '숨어있는 닭도 있습니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '3', x: 0.2, y: 0.6 },
      { id: 'b', label: '5', x: 0.4, y: 0.6 },
      { id: 'c', label: '7', x: 0.6, y: 0.6 },
      { id: 'd', label: '9', x: 0.8, y: 0.6 },
    ],
    correctIds: ['d'],
    explanation: '숨어있는 닭까지 모두 세면 9마리!',
    difficulty: 3,
  },
  {
    id: 17,
    question: '다음 중 가장 싼 것은?',
    hint: '"공짜"라는 글자를 찾아보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '💎 ₩50,000', x: 0.25, y: 0.35 },
      { id: 'b', label: '👑 ₩30,000', x: 0.75, y: 0.35 },
      { id: 'c', label: '🎁 공짜', x: 0.25, y: 0.6 },
      { id: 'd', label: '🌟 ₩10,000', x: 0.75, y: 0.6 },
    ],
    correctIds: ['c'],
    explanation: '공짜가 가장 싼 것입니다!',
    difficulty: 2,
  },
  {
    id: 18,
    question: 'A가 B보다 빠르고, B가 C보다 빠릅니다.\n가장 느린 것은?',
    hint: 'C가 가장 느립니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: 'A', x: 0.25, y: 0.5 },
      { id: 'b', label: 'B', x: 0.5, y: 0.5 },
      { id: 'c', label: 'C', x: 0.75, y: 0.5 },
    ],
    correctIds: ['c'],
    explanation: 'A > B > C이므로 C가 가장 느립니다!',
    difficulty: 2,
  },
  {
    id: 19,
    question: '"사과"라는 글자를 5번 탭하세요',
    hint: '정확히 5번만 탭하세요. 더도 말고 덜도 말고!',
    interaction: 'multi-tap',
    choices: [
      { id: 'apple', label: '🍎 사과', x: 0.5, y: 0.45 },
    ],
    correctIds: ['apple'],
    explanation: '사과를 정확히 5번 탭했습니다!',
    difficulty: 3,
  },
  {
    id: 20,
    question: '빨간 버튼을 3번 누르세요',
    hint: '파란 버튼이 아니라 빨간 버튼입니다',
    interaction: 'multi-tap',
    choices: [
      { id: 'red', label: '🔴', x: 0.35, y: 0.45 },
      { id: 'blue', label: '🔵', x: 0.65, y: 0.45 },
    ],
    correctIds: ['red'],
    explanation: '빨간 버튼을 정확히 3번 눌렀습니다!',
    difficulty: 2,
  },

  // ─── Stage 5: Medium (difficulty 2-3) ─────────────────
  {
    id: 21,
    question: '영어 알파벳에서 가장 많은 물이 있는 글자는?',
    hint: 'C(sea)를 생각해보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: 'A', x: 0.15, y: 0.5 },
      { id: 'b', label: 'B', x: 0.35, y: 0.5 },
      { id: 'c', label: 'C', x: 0.55, y: 0.5 },
      { id: 'd', label: 'D', x: 0.75, y: 0.5 },
    ],
    correctIds: ['c'],
    explanation: 'C는 "sea(바다)"와 발음이 같습니다!',
    difficulty: 3,
  },
  {
    id: 22,
    question: '다음 수식을 완성하세요: 8 + ? = 91',
    hint: '8을 뒤집으면...',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '83', x: 0.2, y: 0.5 },
      { id: 'b', label: '82', x: 0.4, y: 0.5 },
      { id: 'c', label: '11', x: 0.6, y: 0.5 },
      { id: 'd', label: '83', x: 0.8, y: 0.5 },
    ],
    correctIds: ['a'],
    explanation: '8 + 83 = 91',
    difficulty: 2,
  },
  {
    id: 23,
    question: '1=5, 2=25, 3=125, 4=625, 5=?',
    hint: '첫 번째 줄을 잘 보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '3125', x: 0.2, y: 0.5 },
      { id: 'b', label: '1', x: 0.4, y: 0.5 },
      { id: 'c', label: '25', x: 0.6, y: 0.5 },
      { id: 'd', label: '5', x: 0.8, y: 0.5 },
    ],
    correctIds: ['b'],
    explanation: '1=5이면 5=1입니다! 역으로 생각하세요.',
    difficulty: 3,
  },
  {
    id: 24,
    question: '과일 중에서 가장 힘이 센 것은?',
    hint: '파워(power)와 관련된 과일이 있나요?',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🍎 사과', x: 0.2, y: 0.4 },
      { id: 'b', label: '🍌 바나나', x: 0.5, y: 0.4 },
      { id: 'c', label: '🍇 포도', x: 0.8, y: 0.4 },
      { id: 'd', label: '🥝 키위', x: 0.5, y: 0.65 },
    ],
    correctIds: ['b'],
    explanation: '바나나는 "반하나" → 반 + 하나 = 힘이 세다! (말장난)',
    difficulty: 3,
  },
  {
    id: 25,
    question: '시계가 3시를 가리킬 때, 시침과 분침이 이루는 각도는?',
    hint: '3시에서 시침은 3, 분침은 12를 가리킵니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '60°', x: 0.2, y: 0.5 },
      { id: 'b', label: '90°', x: 0.4, y: 0.5 },
      { id: 'c', label: '120°', x: 0.6, y: 0.5 },
      { id: 'd', label: '180°', x: 0.8, y: 0.5 },
    ],
    correctIds: ['b'],
    explanation: '3시에는 시침과 분침이 직각(90°)을 이룹니다!',
    difficulty: 2,
  },

  // ─── Stage 6: Hard (difficulty 3) ─────────────────────
  {
    id: 26,
    question: '달걀이 100개 있었는데 2개가 깨졌고,\n2개를 삶고, 2개를 먹었다면\n남은 달걀은 몇 개?',
    hint: '깨진 것을 삶고, 삶은 것을 먹었다면...',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '94', x: 0.2, y: 0.6 },
      { id: 'b', label: '96', x: 0.4, y: 0.6 },
      { id: 'c', label: '98', x: 0.6, y: 0.6 },
      { id: 'd', label: '97', x: 0.8, y: 0.6 },
    ],
    correctIds: ['c'],
    explanation: '깨진 2개를 삶고 → 삶은 2개를 먹었으므로 98개!',
    difficulty: 3,
  },
  {
    id: 27,
    question: '버스에 7명이 타고 있습니다.\n3명이 내리고 5명이 탔습니다.\n버스 정류장은 총 몇 개 지났나요?',
    hint: '한 번 정차했습니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '1', x: 0.2, y: 0.5 },
      { id: 'b', label: '2', x: 0.4, y: 0.5 },
      { id: 'c', label: '3', x: 0.6, y: 0.5 },
      { id: 'd', label: '15', x: 0.8, y: 0.5 },
    ],
    correctIds: ['a'],
    explanation: '한 정류장에서 3명이 내리고 5명이 탔으므로 1개!',
    difficulty: 3,
  },
  {
    id: 28,
    question: '잠자는 고양이를 깨우세요',
    hint: '고양이를 여러 번 탭해보세요',
    interaction: 'multi-tap',
    choices: [
      { id: 'cat', label: '😺', x: 0.5, y: 0.45 },
    ],
    correctIds: ['cat'],
    explanation: '고양이를 3번 탭해서 깨웠습니다!',
    difficulty: 3,
  },
  {
    id: 29,
    question: '100을 반으로 나누면?',
    hint: '100을 정확히 반으로 가르면...',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '50', x: 0.2, y: 0.5 },
      { id: 'b', label: '1 | 00', x: 0.4, y: 0.5 },
      { id: 'c', label: '10', x: 0.6, y: 0.5 },
      { id: 'd', label: '25', x: 0.8, y: 0.5 },
    ],
    correctIds: ['a'],
    explanation: '100 ÷ 2 = 50입니다!',
    difficulty: 2,
  },
  {
    id: 30,
    question: '다음 중 가장 무거운 것은?',
    hint: '단위를 잘 보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '100g 솜', x: 0.25, y: 0.35 },
      { id: 'b', label: '100g 돌', x: 0.75, y: 0.35 },
      { id: 'c', label: '100g 쇠', x: 0.25, y: 0.6 },
      { id: 'd', label: '모두 같다', x: 0.75, y: 0.6 },
    ],
    correctIds: ['d'],
    explanation: '모두 100g이므로 무게가 같습니다!',
    difficulty: 3,
  },

  // ─── Stage 7: Hard (difficulty 3-4) ───────────────────
  {
    id: 31,
    question: '3+3÷3+3×3-3 = ?',
    hint: '연산 순서: 곱셈, 나눗셈 먼저!',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '6', x: 0.2, y: 0.5 },
      { id: 'b', label: '10', x: 0.4, y: 0.5 },
      { id: 'c', label: '7', x: 0.6, y: 0.5 },
      { id: 'd', label: '9', x: 0.8, y: 0.5 },
    ],
    correctIds: ['b'],
    explanation: '3+(3÷3)+(3×3)-3 = 3+1+9-3 = 10!',
    difficulty: 3,
  },
  {
    id: 32,
    question: '오늘이 월요일이면, 내일모레의 어제는\n무슨 요일인가요?',
    hint: '차근차근 세어보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '화요일', x: 0.2, y: 0.5 },
      { id: 'b', label: '수요일', x: 0.4, y: 0.5 },
      { id: 'c', label: '목요일', x: 0.6, y: 0.5 },
      { id: 'd', label: '월요일', x: 0.8, y: 0.5 },
    ],
    correctIds: ['a'],
    explanation: '내일모레 = 수요일, 어제 = 화요일!',
    difficulty: 3,
  },
  {
    id: 33,
    question: '세상에서 가장 긴 영어 단어는?',
    hint: 'S로 시작하고 S로 끝나는...',
    interaction: 'tap',
    choices: [
      { id: 'a', label: 'smiles', x: 0.25, y: 0.35 },
      { id: 'b', label: 'supercalifragilistic', x: 0.75, y: 0.35 },
      { id: 'c', label: 'pneumono...scopic', x: 0.25, y: 0.6 },
      { id: 'd', label: 'antidisestablishment', x: 0.75, y: 0.6 },
    ],
    correctIds: ['a'],
    explanation: 'smiles! s와 s 사이에 1 mile이 있으니까!',
    difficulty: 4,
  },
  {
    id: 34,
    question: '12시간 동안 시계의 시침과 분침은\n몇 번 겹치나요?',
    hint: '1시간에 한 번씩이지만, 11시와 12시 사이는...',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '10', x: 0.2, y: 0.5 },
      { id: 'b', label: '11', x: 0.4, y: 0.5 },
      { id: 'c', label: '12', x: 0.6, y: 0.5 },
      { id: 'd', label: '22', x: 0.8, y: 0.5 },
    ],
    correctIds: ['b'],
    explanation: '12시간에 11번 겹칩니다 (11시에서 12시 사이는 12시에 1번만)!',
    difficulty: 4,
  },
  {
    id: 35,
    question: '도둑이 들었습니다! 불을 켜세요',
    hint: '화면 밝기를 올려보세요... 가 아니라, 전구를 탭!',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '💡', x: 0.5, y: 0.45 },
    ],
    correctIds: ['a'],
    explanation: '전구를 탭해서 불을 켰습니다!',
    difficulty: 2,
  },

  // ─── Stage 8: Hard (difficulty 3-4) ───────────────────
  {
    id: 36,
    question: '화면에서 가장 큰 도형을 찾으세요',
    hint: '배경도 도형입니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🔺', x: 0.3, y: 0.35 },
      { id: 'b', label: '⬜', x: 0.7, y: 0.35 },
      { id: 'c', label: '🔴', x: 0.3, y: 0.6 },
      { id: 'd', label: '⬛', x: 0.7, y: 0.6 },
    ],
    correctIds: ['b'],
    explanation: '흰색 사각형(배경)이 가장 큰 도형입니다!',
    difficulty: 3,
  },
  {
    id: 37,
    question: '가위바위보에서 절대 지지 않는 방법은?',
    hint: '혼자서는 질 수 없습니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '✊ 바위', x: 0.2, y: 0.5 },
      { id: 'b', label: '✌️ 가위', x: 0.4, y: 0.5 },
      { id: 'c', label: '🖐️ 보', x: 0.6, y: 0.5 },
      { id: 'd', label: '안 내기', x: 0.8, y: 0.5 },
    ],
    correctIds: ['d'],
    explanation: '안 내면 절대 지지 않습니다!',
    difficulty: 3,
  },
  {
    id: 38,
    question: '피자 한 판을 3번 자르면\n최대 몇 조각이 나올까요?',
    hint: '직선으로 자르되, 겹치게 자르면 더 많이!',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '4', x: 0.2, y: 0.5 },
      { id: 'b', label: '6', x: 0.4, y: 0.5 },
      { id: 'c', label: '7', x: 0.6, y: 0.5 },
      { id: 'd', label: '8', x: 0.8, y: 0.5 },
    ],
    correctIds: ['c'],
    explanation: '직선 3번 자르면 최대 7조각! (1+1+2+3)',
    difficulty: 4,
  },
  {
    id: 39,
    question: '강아지를 찾아주세요',
    hint: '화면을 잘 살펴보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🐱', x: 0.25, y: 0.35 },
      { id: 'b', label: '🐰', x: 0.5, y: 0.35 },
      { id: 'c', label: '🐹', x: 0.75, y: 0.35 },
      { id: 'd', label: '🐶', x: 0.5, y: 0.65 },
    ],
    correctIds: ['d'],
    explanation: '강아지(🐶)를 찾았습니다!',
    difficulty: 2,
  },
  {
    id: 40,
    question: '다음 중 날 수 없는 것은?',
    hint: '날개가 없는 것을 찾으세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🦅 독수리', x: 0.2, y: 0.4 },
      { id: 'b', label: '✈️ 비행기', x: 0.4, y: 0.4 },
      { id: 'c', label: '🐧 펭귄', x: 0.6, y: 0.4 },
      { id: 'd', label: '🦋 나비', x: 0.8, y: 0.4 },
    ],
    correctIds: ['c'],
    explanation: '펭귄은 날개가 있지만 날 수 없습니다!',
    difficulty: 2,
  },

  // ─── Stage 9: Very Hard (difficulty 4) ────────────────
  {
    id: 41,
    question: '어항에 물고기 10마리가 있는데,\n3마리가 죽었습니다. 어항에 몇 마리?',
    hint: '죽은 물고기도 어항에 있습니다',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '7', x: 0.2, y: 0.5 },
      { id: 'b', label: '10', x: 0.4, y: 0.5 },
      { id: 'c', label: '3', x: 0.6, y: 0.5 },
      { id: 'd', label: '0', x: 0.8, y: 0.5 },
    ],
    correctIds: ['b'],
    explanation: '죽은 물고기도 어항에 있으므로 여전히 10마리!',
    difficulty: 4,
  },
  {
    id: 42,
    question: '수박의 반은?',
    hint: '글자를 반으로 나누면...',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '수', x: 0.25, y: 0.5 },
      { id: 'b', label: '박', x: 0.5, y: 0.5 },
      { id: 'c', label: '반쪽 수박', x: 0.75, y: 0.5 },
    ],
    correctIds: ['a'],
    explanation: '"수박"의 반은 "수"입니다! (글자의 반)',
    difficulty: 4,
  },
  {
    id: 43,
    question: '오리 뒤에 소를 놓으면?',
    hint: '오리 + 소 = ?',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '오리소', x: 0.2, y: 0.5 },
      { id: 'b', label: '소오리', x: 0.4, y: 0.5 },
      { id: 'c', label: '오리소리', x: 0.6, y: 0.5 },
      { id: 'd', label: '소리', x: 0.8, y: 0.5 },
    ],
    correctIds: ['a'],
    explanation: '오리 뒤에 소 = "오리소"! (단순하게 생각하세요)',
    difficulty: 3,
  },
  {
    id: 44,
    question: '비가 올 때 올라가는 것은?',
    hint: '우산을 생각해보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '☂️ 우산', x: 0.25, y: 0.4 },
      { id: 'b', label: '🌡️ 습도', x: 0.5, y: 0.4 },
      { id: 'c', label: '💧 물', x: 0.75, y: 0.4 },
    ],
    correctIds: ['a'],
    explanation: '비가 오면 우산이 올라갑니다!',
    difficulty: 3,
  },
  {
    id: 45,
    question: '어두운 방에 성냥, 양초, 랜턴이 있습니다.\n무엇을 먼저 켜야 할까요?',
    hint: '양초나 랜턴을 켜려면 먼저...',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🕯️ 양초', x: 0.25, y: 0.5 },
      { id: 'b', label: '🔦 랜턴', x: 0.5, y: 0.5 },
      { id: 'c', label: '🔥 성냥', x: 0.75, y: 0.5 },
    ],
    correctIds: ['c'],
    explanation: '성냥을 먼저 켜야 다른 것을 켤 수 있습니다!',
    difficulty: 3,
  },

  // ─── Stage 10: Expert (difficulty 4-5) ────────────────
  {
    id: 46,
    question: '1 + 1 = ?',
    hint: '정말 쉬운 문제입니다. 함정이 아닙니다!',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '2', x: 0.2, y: 0.5 },
      { id: 'b', label: '11', x: 0.4, y: 0.5 },
      { id: 'c', label: '윈도우', x: 0.6, y: 0.5 },
      { id: 'd', label: '田', x: 0.8, y: 0.5 },
    ],
    correctIds: ['a'],
    explanation: '1+1=2! 가끔은 정답이 가장 단순합니다.',
    difficulty: 4,
  },
  {
    id: 47,
    question: '당신의 나이에서 1을 빼면?',
    hint: '나이 - 1 = 작년 나이',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '젊어진다', x: 0.25, y: 0.4 },
      { id: 'b', label: '작년 나이', x: 0.5, y: 0.4 },
      { id: 'c', label: '아무 변화 없다', x: 0.75, y: 0.4 },
    ],
    correctIds: ['b'],
    explanation: '나이에서 1을 빼면 작년 나이입니다!',
    difficulty: 3,
  },
  {
    id: 48,
    question: '아무 것도 탭하지 마세요',
    hint: '진짜로 아무 것도 탭하지 마세요!',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '여기 탭!', x: 0.25, y: 0.4 },
      { id: 'b', label: '이거 탭!', x: 0.5, y: 0.4 },
      { id: 'c', label: '나를 탭!', x: 0.75, y: 0.4 },
      { id: 'skip', label: '⏭️ 다음', x: 0.5, y: 0.7 },
    ],
    correctIds: ['skip'],
    explanation: '아무 것도 탭하지 말라고 했으니 다음으로 넘기세요!',
    difficulty: 4,
  },
  {
    id: 49,
    question: '🐔이 🥚를 낳았습니다.\n먼저인 것은?',
    hint: '문제를 다시 읽어보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: '🐔 닭', x: 0.3, y: 0.5 },
      { id: 'b', label: '🥚 달걀', x: 0.7, y: 0.5 },
    ],
    correctIds: ['a'],
    explanation: '문제에서 "닭이 달걀을 낳았다"고 했으므로 닭이 먼저!',
    difficulty: 5,
  },
  {
    id: 50,
    question: '축하합니다! 🎉\n이 게임의 이름은?',
    hint: '화면 위를 보세요',
    interaction: 'tap',
    choices: [
      { id: 'a', label: 'Brain Test', x: 0.25, y: 0.4 },
      { id: 'b', label: 'Brain Out', x: 0.5, y: 0.4 },
      { id: 'c', label: '넌센스 퀴즈', x: 0.75, y: 0.4 },
    ],
    correctIds: ['b'],
    explanation: 'Brain Out! 맞습니다! 🎉',
    difficulty: 1,
  },
];

/** Get puzzles for a specific stage */
export function getPuzzlesForStage(stageNum: number): Puzzle[] {
  const PUZZLES_PER_STAGE = 5;
  const startIdx = (stageNum - 1) * PUZZLES_PER_STAGE;
  const endIdx = Math.min(startIdx + PUZZLES_PER_STAGE, PUZZLES.length);
  return PUZZLES.slice(startIdx, endIdx);
}

/** Get a single puzzle by id */
export function getPuzzleById(id: number): Puzzle | undefined {
  return PUZZLES.find((p) => p.id === id);
}
